In [1]:
import pandas as pd

In [5]:
path = 'first_100_rows.csv'

In [20]:
loans = pd.read_csv(path, header=1, error_bad_lines=False, usecols=[3,5,6,7,8,9,10,11,12,13,14,15,16,20,21,22,23,24,36,38,40,45,46,47])
loans.head()

,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,title,zip_code,addr_state,dti,out_prncp,total_pymnt,total_rec_prncp,last_pymnt_d,last_pymnt_amnt,next_pymnt_d
0,9000,36 months,15.31%,313.36,C,C5,Senior Case Assistant,9 years,RENT,52000,...,Debt consolidation,945xx,CA,18.86,0.00,10193.65174,9000.00,Mar-17,7064.14,NaN
1,8000,36 months,10.75%,260.97,B,B4,Vp,5 years,RENT,73000,...,Debt consolidation,917xx,CA,10.85,769.43,8638.28000,7230.57,Jan-19,260.97,Feb-19
2,11275,36 months,15.31%,392.57,C,C5,Licensing Specialist,< 1 year,MORTGAGE,35000,...,Credit card refinancing,275xx,NC,20.47,0.00,13662.78416,11275.00,Feb-18,5437.99,NaN
3,12800,36 months,11.99%,425.09,C,C1,LOGISTICS COORDINATOR,6 years,MORTGAGE,53000,...,Credit card refinancing,330xx,FL,20.99,1249.88,14014.88000,11550.12,Jan-19,425.09,Feb-19
4,9600,36 months,9.75%,308.64,B,B3,unit leader,10+ years,MORTGAGE,120000,...,Home improvement,835xx,ID,13.11,0.00,10932.38387,9600.00,Mar-18,4115.59,NaN

In [4]:
path = 'LoanStats_2016Q1.csv'

In [6]:
loans = pd.read_csv(path, header=1, error_bad_lines=False, 
                    usecols=[3,5,6,7,8,9,10,11,12,13,14,15,16,20,21,22,23,24,36,38,40,45,46,47])
loans.head()

,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,title,zip_code,addr_state,dti,out_prncp,total_pymnt,total_rec_prncp,last_pymnt_d,last_pymnt_amnt,next_pymnt_d
0,9000.0,36 months,15.31%,313.36,C,C5,Senior Case Assistant,9 years,RENT,52000.0,...,Debt consolidation,945xx,CA,18.86,0.00,10193.65174,9000.00,Mar-17,7064.14,NaN
1,8000.0,36 months,10.75%,260.97,B,B4,Vp,5 years,RENT,73000.0,...,Debt consolidation,917xx,CA,10.85,769.43,8638.28000,7230.57,Jan-19,260.97,Feb-19
2,11275.0,36 months,15.31%,392.57,C,C5,Licensing Specialist,< 1 year,MORTGAGE,35000.0,...,Credit card refinancing,275xx,NC,20.47,0.00,13662.78416,11275.00,Feb-18,5437.99,NaN
3,12800.0,36 months,11.99%,425.09,C,C1,LOGISTICS COORDINATOR,6 years,MORTGAGE,53000.0,...,Credit card refinancing,330xx,FL,20.99,1249.88,14014.88000,11550.12,Jan-19,425.09,Feb-19
4,9600.0,36 months,9.75%,308.64,B,B3,unit leader,10+ years,MORTGAGE,120000.0,...,Home improvement,835xx,ID,13.11,0.00,10932.38387,9600.00,Mar-18,4115.59,NaN

In [7]:
loans.to_csv('loans.sqlite')